---
parserOptions:
  ecmaVersion: 9
  sourceType: "module"
env:
  commonjs: true
  node: true
  es6: true
rules:
  strict:
    - 2
    - "global"
  quotes:
    - 2
    - "single"
    -
      allowTemplateLiterals: true
  new-cap: 0
  camelcase: 0
  no-unused-vars: "error"
  no-undef: "error"
