version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.2

    working_directory: ~/repo

    environment:
      SOURCE_MOUNT: --volumes_from=source

    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker create -v /src --name source alpine /bin/true
          docker cp . source:/src

      # TODO: Figure out node.js caching here

      - run: npm install

      - run: npm test
