version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.2

    working_directory: ~/repo

    environment:
      SOURCE_MOUNT: --volumes-from=source

    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker create -v /src/tupelo --name source alpine /bin/true
          docker cp . source:/src/tupelo

      # TODO: Figure out node.js caching here

      - run: npm install

      - run: npm test
